### ISSUE TITLE
Error if the target directory doesn't already exist.

### ISSUE THREAD

**Issue by fahrradflucht** [jonathanargentiero/ejs-webpack-builder#1]
The plugin errors out if the target dir doesn't already exist. Thats not very practical if you want to write to your build dir and you make a clean build.

**Comment by jonathanargentiero** [comment]
Right, I've missed that. Thanks for the report!

**Comment by fahrradflucht** [comment]
Fixed with e510708c8c6d3aad20f7b2555ed26e03a54046d1.
