### ISSUE TITLE
Change to webpack emit.

### ISSUE THREAD

**Issue by fahrradflucht** [jonathanargentiero/ejs-webpack-builder#3]
I changed the plugin behavior so that it emits the build files _the official way_ in [this branch of my fork](https://github.com/Fahrradflucht/ejs-webpack-builder/tree/change-to-webpack-emit).

Is this something you would like to merge into the project? Note that it introduces a breaking change to the config in it's current state.

**Comment by jonathanargentiero** [comment]
I looked at the commit and it's fine.
It would be great to have some UT at a certain point to add Travis, but it's fine for the moment.
Let's go with a PR.
